import {initViewSelect} from "./view-select.js";
import { initEventCreateButtons } from "./even-create-button.js";
import { initEventFormDialog } from "./event-form-dialog.js";
import { initEventStore } from "./event-store.js";
import { initNotification } from "./notification.js";
import {initCalendar} from "./calender.js";
import { initNav } from "./nav.js";
import { initEventDetailsDialog } from "./event-details-dialog.js";
import { initEventDeleteDialog } from "./event-delete-dialog.js";
import { initMiniCalendars } from "./mini-calendar.js";
import { initResponsive } from "./responsive.js";
import { initHamburger } from "./hamburger.js";
import { initMobileSideBar } from "./mobile-sidebar.js";
import { initUrl } from "./url.js";
import { initSync } from "./sync.js";

const eventStore = initEventStore();
initCalendar(eventStore);
initEventCreateButtons();
initEventFormDialog();
initEventDetailsDialog();
initNotification();
initViewSelect();
initNav();
initEventDeleteDialog();
initMiniCalendars();
initResponsive();
initHamburger();
initMobileSideBar();
initUrl();
initSync();